# Export scientific figures and a self-contained, editable HTML analysis report.
# All figures use the selected reference *background*, the same contour
# thresholds and the displayed coordinates; numerical data is not rounded
# until writing a human-readable table.

ram_draw_figure <- function(data, reference, colors, chain_colors,
                            title = "RamplotR | Ramachandran analysis",
                            use_raster = FALSE) {
  stopifnot(length(colors) == 4L, is.matrix(reference$z))
  limits <- ram_density_thresholds(reference)
  z <- reference$z
  code <- matrix(1L, nrow(z), ncol(z))
  code[z > limits[[3L]]] <- 2L
  code[z > limits[[2L]]] <- 3L
  code[z > limits[[1L]]] <- 4L
  graphics::par(mar = c(4.7, 4.7, 2.8, 2.0), bg = "white")
  graphics::image(
    x = reference$x, y = reference$y, z = t(code),
    col = as.character(colors), breaks = seq(0.5, 4.5, by = 1),
    xlim = c(-180, 180), ylim = c(-180, 180), asp = 1,
    xlab = expression(phi~"(degrees)"), ylab = expression(psi~"(degrees)"),
    main = title, axes = FALSE, useRaster = use_raster
  )
  graphics::axis(1, at = c(-180, -90, 0, 90, 180))
  graphics::axis(2, at = c(-180, -90, 0, 90, 180), las = 1)
  graphics::box(col = "#9DB7B8")
  graphics::abline(h = 0, v = 0, col = "#B5CBCA", lty = 2)
  valid <- is.finite(data$phi) & is.finite(data$psi)
  present <- unique(as.character(data$chain[valid]))
  for (i in seq_along(present)) {
    rows <- which(valid & data$chain == present[[i]])
    chain_index <- match(present[[i]], names(chain_colors))
    color <- if (!is.na(chain_index)) chain_colors[[chain_index]] else
      c("#D57359", "#307D99", "#80649A", "#BF8E40")[[((i - 1L) %% 4L) + 1L]]
    graphics::points(data$phi[rows], data$psi[rows],
                     pch = 21, cex = 0.65, bg = color,
                     col = "#FFFFFF", lwd = 0.35)
  }
  if (length(present) && length(present) <= 8L) {
    graphics::legend("topright", legend = paste("Chain", present),
                     pch = 21, pt.bg = vapply(present, function(chain) {
                       if (chain %in% names(chain_colors))
                         chain_colors[[chain]] else "#4D8F96"
                     }, character(1)), bty = "n", cex = 0.7)
  }
}

ram_save_figure <- function(path, data, reference, colors, chain_colors,
                            format = c("svg", "png"), title = "RamplotR") {
  format <- match.arg(format)
  if (format == "svg") {
    grDevices::svg(path, width = 7.1, height = 7.1, pointsize = 10)
  } else {
    grDevices::png(path, width = 2200, height = 2200, res = 300,
                   type = if (capabilities("cairo")) "cairo" else "Xlib")
  }
  on.exit(grDevices::dev.off(), add = TRUE)
  ram_draw_figure(data, reference, colors, chain_colors, title,
                  use_raster = identical(format, "png"))
  invisible(path)
}

ram_report_metadata <- function(name, reference_set, background,
                                validation_mode, model, reference_file) {
  list(
    structure = name,
    reference_set = reference_set,
    displayed_background = background,
    classification = validation_mode,
    model = as.character(model),
    reference_md5 = if (file.exists(reference_file))
      unname(tools::md5sum(reference_file)) else "unavailable",
    generated_utc = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"),
    R_version = R.version.string,
    bio3d_version = as.character(utils::packageVersion("bio3d"))
  )
}

ram_save_html_report <- function(path, data, metadata, svg_path,
                                 max_report_rows = 10000L) {
  esc <- htmltools::htmlEscape
  h <- function(label, value) {
    htmltools::tags$tr(htmltools::tags$th(label),
                       htmltools::tags$td(as.character(value)))
  }
  summary_regions <- c("Favoured", "Allowed", "Generously allowed", "Not allowed")
  tally <- vapply(summary_regions,
                  function(value) sum(data$region == value, na.rm = TRUE),
                  integer(1))
  counts <- lapply(seq_along(tally), function(k)
    h(summary_regions[[k]], tally[[k]]))
  totals <- list(h("Missing angles", sum(is.na(data$phi) | is.na(data$psi))),
                 h("All selected residues", nrow(data)))
  meta <- lapply(names(metadata), function(k)
    h(gsub("_", " ", k), metadata[[k]]))
  shown <- utils::head(data[, intersect(
    c("chain", "resi", "insertion_code", "resn", "phi", "psi", "region", "density", "plddt", "confidence_category"),
    colnames(data)), drop = FALSE], max_report_rows)
  if ("phi" %in% names(shown)) shown$phi <- round(shown$phi, 2)
  if ("psi" %in% names(shown)) shown$psi <- round(shown$psi, 2)
  if ("density" %in% names(shown)) shown$density <- round(shown$density, 2)
  lines <- readLines(svg_path, warn = FALSE)
  # SVG is generated by this application, not loaded from an arbitrary source.
  chart <- htmltools::HTML(paste(lines[!grepl("^<\\?xml", lines)], collapse="\n"))
  doc <- htmltools::tags$html(
    htmltools::tags$head(
      htmltools::tags$meta(charset = "UTF-8"),
      htmltools::tags$title("RamplotR structure analysis"),
      htmltools::tags$style(htmltools::HTML(
        "body{font:15px system-ui,sans-serif;margin:3em auto;max-width:1000px;color:#18323b}h1,h2{color:#146a70}table{border-collapse:collapse;width:100%}th,td{padding:6px 12px;border-bottom:1px solid #dbe6e6;text-align:left}th{background:#eef6f4}svg{width:min(100%,760px);height:auto}p.note{color:#516b74}section{margin:2em 0}"
      ))
    ),
    htmltools::tags$body(
      htmltools::tags$h1("RamplotR structure analysis"),
      htmltools::tags$p(class = "note",
        "Portable report: figure, counts, classifications and reproducibility settings."),
      htmltools::tags$section(htmltools::tags$h2("Ramachandran plot"), chart),
      htmltools::tags$section(htmltools::tags$h2("Region counts"),
                             htmltools::tags$table(c(counts, totals))),
      htmltools::tags$section(htmltools::tags$h2("Analysis provenance"),
                             htmltools::tags$table(meta)),
      htmltools::tags$section(htmltools::tags$h2("Residue details"),
        if (nrow(data) > max_report_rows) htmltools::tags$p(class="note",
          sprintf("Showing the first %s of %s residues; export the CSV for all rows.",
                  max_report_rows, nrow(data))),
        htmltools::tags$table(
          htmltools::tags$thead(htmltools::tags$tr(
            lapply(names(shown), htmltools::tags$th))),
          htmltools::tags$tbody(lapply(seq_len(nrow(shown)), function(i)
            htmltools::tags$tr(lapply(shown[i, ], function(value)
              htmltools::tags$td(if (is.na(value)) "" else as.character(value))))))))
    )
  )
  writeLines(as.character(doc), path, useBytes = TRUE)
  invisible(path)
}
